"$schema" = "node_modules/wrangler/config-schema.json"
name = "user-post"
main = ".output/server/index.mjs"
compatibility_date = "2025-07-24"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true
