FROM node:20-alpine

WORKDIR /app

# Install nodemon globally for development
RUN npm install -g nodemon tsx

COPY package*.json ./
RUN npm install

# Create directory for database
RUN mkdir -p var/data

#add database to the database directory
RUN mkdir -p var/data/db

EXPOSE 5003

CMD ["npm", "run", "dev"]
